// Metadata only: importing the selector must never import datetime implementations.
export const libraries = [
  {
    id: "native-temporal",
    label: "Native Temporal",
    entry: "",
    imports: "",
    now: "Temporal.Now.zonedDateTimeISO()",
    type: "Temporal.ZonedDateTime",
    packages: "",
  },
  {
    id: "temporal-polyfill",
    label: "temporal-polyfill",
    entry: "/temporal-polyfill",
    imports: 'import { Temporal } from "temporal-polyfill";',
    now: "Temporal.Now.zonedDateTimeISO()",
    type: "Temporal.ZonedDateTime",
    packages: "temporal-polyfill",
  },
  {
    id: "js-temporal-polyfill",
    label: "@js-temporal/polyfill",
    entry: "/js-temporal-polyfill",
    imports: 'import { Temporal } from "@js-temporal/polyfill";',
    now: "Temporal.Now.zonedDateTimeISO()",
    type: "Temporal.ZonedDateTime",
    packages: "@js-temporal/polyfill",
  },
  {
    id: "luxon",
    label: "Luxon",
    entry: "/luxon",
    imports: 'import { DateTime } from "luxon";',
    now: "DateTime.now()",
    type: "DateTime",
    packages: "luxon",
  },
  {
    id: "moment",
    label: "Moment",
    entry: "/moment",
    imports: 'import moment from "moment";',
    now: "moment()",
    type: "moment.Moment",
    packages: "moment",
  },
  {
    id: "dayjs",
    label: "Day.js",
    entry: "/dayjs",
    imports: 'import dayjs from "dayjs";',
    now: "dayjs()",
    type: "dayjs.Dayjs",
    packages: "dayjs",
  },
  {
    id: "date-fns",
    label: "date-fns",
    entry: "/date-fns",
    imports: "",
    now: "new Date()",
    type: "Date",
    packages: "date-fns @date-fns/tz",
  },
  {
    id: "spacetime",
    label: "Spacetime",
    entry: "/spacetime",
    imports: 'import spacetime from "spacetime";',
    now: "spacetime.now()",
    type: "ReturnType<typeof spacetime>",
    packages: "spacetime",
  },
  {
    id: "internationalized-date",
    label: "@internationalized/date",
    entry: "/internationalized-date",
    imports: 'import { now, getLocalTimeZone, type ZonedDateTime } from "@internationalized/date";',
    now: "now(getLocalTimeZone())",
    type: "ZonedDateTime",
    packages: "@internationalized/date",
  },
] as const;
export type LibraryId = (typeof libraries)[number]["id"];
export const libraryPath = (id: LibraryId) => `/${id}/`;
